### ISSUE TITLE
I don't know how to fix  the indentation and I couldn't match screen 400px

### ISSUE THREAD

**Issue by Samirahajiragab** [Samirahajiragab/more-than-just-datum#1]
<img width="520" alt="image" src="https://user-images.githubusercontent.com/55094325/79332957-b9552200-7eeb-11ea-8b2e-70ab43cd87a5.png">
@muxlowc

**Comment by muxlowc** [comment]
@Samirahajiragab 

1) You have a typo for that section `<section class="gird grid-stretch">` should be grid, not gird
2) you currently have your dd/dts not set in a list, so you'll need to wrap them inside of a `<dl>`
3) those `<dl>`s are actually inside of another list. Here's the code to get you started:

```
<ul class="near-list list-group push-0">
        <li class="card island-1-2 push-1-2">
          <h3 class="mega push-0">373</h3>
          <dl class="list-group-inline push-0">
            <dt class="push-0 italic milli">Distance</dt>
            <dd class="push-0">0.75 km</dd>
          </dl>
        </li>
```
You can see that there are 3 items inside of an unordered list, and inside each item, there is a `<dl>` with three items in that.
